import { useEffect, useState, type ReactNode } from "react";

const IMG = "/__mockup/images/";

function Icon({ kind }: { kind: "heart" | "search" | "user" | "bag" | "menu" | "close" }) {
  const paths = {
    heart: <path d="M12 20.5S4 15.6 4 9.6a4.2 4.2 0 0 1 8-1.8 4.2 4.2 0 0 1 8 1.8c0 6-8 10.9-8 10.9Z" />,
    search: <><circle cx="10.8" cy="10.8" r="6.2" /><path d="m16 16 4.5 4.5" /></>,
    user: <><circle cx="12" cy="8" r="3.2" /><path d="M5.5 20c.7-3.6 2.9-5.4 6.5-5.4s5.8 1.8 6.5 5.4" /></>,
    bag: <><path d="M5.5 8.5h13l-1 12h-11l-1-12Z" /><path d="M9 9V6a3 3 0 0 1 6 0v3" /></>,
    menu: <><path d="M4 8h16M4 16h16" /></>,
    close: <><path d="m6 6 12 12M18 6 6 18" /></>,
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" className="ar-icon">{paths[kind]}</svg>;
}

function Eyebrow({ children }: { children: ReactNode }) {
  return <p className="ar-eyebrow">{children}</p>;
}

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`ar-reveal ${className}`}>{children}</div>;
}

export function AVELINRougeHomepage() {
  const [scrolled, setScrolled] = useState(false);
  const [menu, setMenu] = useState(false);
  const [search, setSearch] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 24);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const closeMenu = () => setMenu(false);
  return (
    <div className="ar-page">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&family=Playfair+Display:wght@400;500;600&display=swap');
        :root { --ox:#4A1420; --burg:#5C1F2E; --gold:#B08D57; --mgold:#9C7A4A; --ivory:#F7F1E6; --cream:#F0E8D8; --earth:#6B4E3D; --char:#2A2624; --black:#16130F; --warm:#FDFBF8; }
        *{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;background:var(--ivory);color:var(--char);font-family:'DM Sans',sans-serif;font-weight:400}
        .ar-page{overflow:hidden;background:var(--ivory)} .ar-icon{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.15;stroke-linecap:square;stroke-linejoin:miter}
        .ar-nav{position:fixed;z-index:20;top:0;left:0;width:100%;height:88px;padding:0 clamp(22px,4vw,64px);display:flex;align-items:center;justify-content:space-between;color:var(--warm);transition:background .5s ease,color .5s ease,border-color .5s ease;border-bottom:1px solid transparent}
        .ar-nav.is-scrolled{background:rgba(247,241,230,.97);color:var(--char);border-color:rgba(74,20,32,.16);backdrop-filter:blur(12px)}
        .ar-wordmark{font-family:'Playfair Display',serif;font-size:20px;letter-spacing:.25em;color:inherit;text-decoration:none;white-space:nowrap}.ar-wordmark small{display:block;font-family:'DM Sans',sans-serif;font-size:7px;letter-spacing:.38em;text-align:center;color:var(--gold);margin-top:3px}
        .ar-links{display:flex;gap:clamp(23px,3vw,48px);margin-left:8vw}.ar-links a,.ar-utils button{position:relative;color:inherit;text-decoration:none;font-size:10px;letter-spacing:.19em;text-transform:uppercase;background:none;border:0;padding:8px 0;cursor:pointer}.ar-links a:after,.ar-footer a:after{content:"";position:absolute;bottom:1px;left:0;width:0;height:1px;background:var(--gold);transition:width .3s ease}.ar-links a:hover:after,.ar-footer a:hover:after{width:100%}
        .ar-utils{display:flex;align-items:center;gap:20px}.ar-utils button{display:grid;place-items:center}.ar-menu-btn{display:none}
        .ar-hero{height:100svh;min-height:680px;position:relative;background:var(--ox);color:var(--warm);display:flex;align-items:flex-end}.ar-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(22,19,15,.3),rgba(22,19,15,.08) 45%,rgba(22,19,15,.67));pointer-events:none}.ar-hero-img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;filter:saturate(.7) contrast(.94);animation:ar-breathe 18s ease-out both}.ar-hero-content{position:relative;z-index:1;padding:0 clamp(24px,7vw,112px) clamp(48px,8vw,100px);max-width:880px}.ar-hero-kicker{font-size:10px;letter-spacing:.35em;color:#d4ba88;text-transform:uppercase;margin-bottom:22px}.ar-hero h1{font-family:'Playfair Display',serif;font-weight:400;font-size:clamp(58px,10vw,145px);line-height:.88;letter-spacing:-.055em;margin:0 0 33px}.ar-hero h1 em{font-style:italic;color:#eadcc3}.ar-hero-note{font-size:11px;letter-spacing:.12em;line-height:1.7;max-width:250px;color:#e8dfd2}.ar-scroll{position:absolute;z-index:2;right:clamp(24px,4vw,64px);bottom:56px;writing-mode:vertical-rl;text-transform:uppercase;letter-spacing:.22em;font-size:9px;color:#e6d6b7}.ar-scroll:after{content:"";display:inline-block;height:47px;width:1px;background:var(--gold);margin-top:13px}
        .ar-section{padding:clamp(88px,12vw,176px) clamp(24px,7vw,112px)}.ar-story{display:grid;grid-template-columns:repeat(12,1fr);gap:32px;align-items:center;background:var(--ivory)}.ar-story-copy{grid-column:2 / span 5}.ar-story-image{grid-column:8 / span 4;position:relative}.ar-story-image img{width:100%;aspect-ratio:3/4;object-fit:cover;filter:saturate(.65)}.ar-story-image:before{content:"";position:absolute;inset:-24px 24px 24px -24px;border:1px solid var(--gold);z-index:0}.ar-story-image img{position:relative;z-index:1}.ar-eyebrow{font-size:9px;letter-spacing:.28em;text-transform:uppercase;color:var(--mgold);margin:0 0 25px}.ar-display{font-family:'Playfair Display',serif;font-weight:400;color:var(--burg);font-size:clamp(38px,5.2vw,75px);line-height:1.02;letter-spacing:-.04em;margin:0 0 29px}.ar-body{font-size:14px;line-height:1.85;color:var(--earth);max-width:430px}.ar-link{display:inline-flex;margin-top:30px;color:var(--burg);font-size:10px;letter-spacing:.22em;text-transform:uppercase;text-decoration:none;border-bottom:1px solid var(--gold);padding-bottom:8px}
        .ar-vision{background:var(--cream);display:grid;grid-template-columns:repeat(12,1fr);gap:32px;align-items:center}.ar-vision-image{grid-column:2 / span 4;position:relative}.ar-vision-image img{width:100%;aspect-ratio:4/5;object-fit:cover;filter:saturate(.6)}.ar-vision-copy{grid-column:7 / span 5}.ar-quote{font-family:'Playfair Display',serif;color:var(--burg);font-size:clamp(28px,3.5vw,50px);line-height:1.2;margin:0 0 33px}.ar-signature{font-family:'Playfair Display',serif;font-style:italic;color:var(--earth);font-size:19px}.ar-pillars{background:var(--burg);color:var(--ivory);padding-bottom:clamp(100px,13vw,190px)}.ar-pillars .ar-eyebrow{color:#d4ba88}.ar-pillars .ar-display{color:var(--ivory);max-width:500px}.ar-pillar-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:1px;margin-top:68px;border-top:1px solid rgba(240,232,216,.35)}.ar-pillar{padding:31px 32px 10px 0;border-right:1px solid rgba(240,232,216,.25);min-height:220px}.ar-pillar:last-child{border:0;padding-left:32px}.ar-pillar:nth-child(2){padding-left:32px}.ar-pillar-index{font-size:10px;color:#d4ba88;letter-spacing:.2em}.ar-pillar h3{font-family:'Playfair Display',serif;font-weight:400;font-size:27px;margin:46px 0 15px}.ar-pillar p{font-size:12px;line-height:1.75;color:#dfd2c0;max-width:220px}
        .ar-collections{background:var(--warm);padding-bottom:clamp(105px,14vw,190px)}.ar-collection-intro{display:flex;justify-content:space-between;align-items:end;margin-bottom:68px}.ar-collection-intro .ar-display{margin:0}.ar-collection-grid{display:grid;grid-template-columns:1.15fr .8fr .95fr;gap:20px;align-items:start}.ar-collection{display:block;color:inherit;text-decoration:none}.ar-collection:nth-child(2){margin-top:86px}.ar-collection:nth-child(3){margin-top:25px}.ar-collection-visual{overflow:hidden;background:var(--cream)}.ar-collection img{display:block;width:100%;aspect-ratio:3/4;object-fit:cover;filter:saturate(.65);transition:transform 1.1s cubic-bezier(.2,.7,.2,1)}.ar-collection:hover img{transform:scale(1.045)}.ar-collection:nth-child(2) img{aspect-ratio:4/5}.ar-collection:nth-child(3) img{aspect-ratio:3/4}.ar-collection-label{padding-top:19px;display:flex;justify-content:space-between;align-items:center}.ar-collection-label h3{font-family:'Playfair Display',serif;font-weight:400;font-size:21px;color:var(--burg);margin:0}.ar-collection-label span{font-size:9px;letter-spacing:.17em;color:var(--mgold)}
        .ar-atelier{background:var(--cream);display:grid;grid-template-columns:repeat(12,1fr);gap:32px;align-items:center}.ar-atelier-copy{grid-column:2 / span 4}.ar-atelier-image{grid-column:7 / span 6;position:relative}.ar-atelier-image img{width:100%;aspect-ratio:16/10;object-fit:cover;filter:saturate(.62)}.ar-atelier-meta{position:absolute;bottom:-34px;left:-40px;background:var(--ox);color:var(--ivory);padding:22px 28px;font-family:'Playfair Display',serif;font-size:18px}.ar-appointment{background:var(--ox);color:var(--ivory);text-align:center;padding:clamp(110px,15vw,215px) 24px}.ar-appointment .ar-eyebrow{color:#d4ba88}.ar-appointment .ar-display{color:var(--ivory);max-width:730px;margin:0 auto 35px}.ar-appointment p{color:#dfd2c0;max-width:380px;margin:0 auto;line-height:1.8;font-size:13px}.ar-cta{display:inline-block;color:var(--ivory);border:1px solid var(--gold);padding:17px 30px;margin-top:38px;text-decoration:none;text-transform:uppercase;font-size:10px;letter-spacing:.25em;transition:background .3s,color .3s}.ar-cta:hover{background:var(--gold);color:var(--black)}
        .ar-footer{background:var(--black);color:var(--ivory);padding:44px clamp(24px,7vw,112px) 30px;display:grid;grid-template-columns:1fr auto 1fr;align-items:end}.ar-footer .ar-wordmark{font-size:16px}.ar-footer nav{display:flex;gap:28px}.ar-footer a{position:relative;color:#d3c8b9;text-decoration:none;font-size:9px;letter-spacing:.18em;text-transform:uppercase}.ar-footer small{justify-self:end;color:#8e8176;font-size:9px;letter-spacing:.1em}
        .ar-search{position:fixed;z-index:30;top:88px;left:0;right:0;background:var(--ivory);border-bottom:1px solid rgba(74,20,32,.2);padding:30px clamp(24px,7vw,112px);transform:translateY(-120%);opacity:0;visibility:hidden;pointer-events:none;transition:transform .45s ease,opacity .3s ease,visibility .3s ease}.ar-search.open{transform:translateY(0);opacity:1;visibility:visible;pointer-events:auto}.ar-search label{display:block;color:var(--mgold);font-size:9px;letter-spacing:.25em;text-transform:uppercase;margin-bottom:14px}.ar-search input{width:100%;border:0;border-bottom:1px solid var(--earth);background:transparent;padding:9px 0;color:var(--burg);font:400 25px 'Playfair Display',serif;outline:none}.ar-mobile-menu{display:none}
        .ar-reveal{animation:ar-reveal .9s ease both}@keyframes ar-reveal{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}@keyframes ar-breathe{from{transform:scale(1.04)}to{transform:scale(1)}}@media (prefers-reduced-motion:reduce){html{scroll-behavior:auto}.ar-hero-img{animation:none}.ar-collection img{transition:none}.ar-search{transition:none}.ar-reveal{animation:none}}
        @media(max-width:760px){.ar-nav{height:72px}.ar-links{display:none}.ar-utils{gap:14px}.ar-utils .ar-menu-btn{display:grid}.ar-utils .ar-menu-btn{order:5}.ar-utils button:nth-child(1),.ar-utils button:nth-child(2){display:none}.ar-wordmark{font-size:17px}.ar-hero{min-height:620px}.ar-hero-content{padding-bottom:70px}.ar-hero h1{font-size:clamp(54px,16vw,86px)}.ar-scroll{display:none}.ar-section{padding:92px 24px}.ar-story,.ar-vision,.ar-atelier{display:flex;flex-direction:column;gap:52px;align-items:stretch}.ar-story-copy,.ar-vision-copy,.ar-atelier-copy,.ar-story-image,.ar-vision-image,.ar-atelier-image{width:100%}.ar-story-copy{order:1}.ar-story-image{order:2;margin:0 10px;width:calc(100% - 10px)}.ar-vision-image{order:2;width:80%;margin-left:auto}.ar-vision-copy{order:1}.ar-pillar-grid{display:block;margin-top:45px}.ar-pillar,.ar-pillar:nth-child(2),.ar-pillar:last-child{border-right:0;border-bottom:1px solid rgba(240,232,216,.25);padding:25px 0;min-height:0}.ar-pillar h3{margin:25px 0 12px}.ar-collection-intro{display:block;margin-bottom:44px}.ar-collection-grid{display:block}.ar-collection,.ar-collection:nth-child(2),.ar-collection:nth-child(3){margin:0 0 52px}.ar-collection img,.ar-collection:nth-child(2) img,.ar-collection:nth-child(3) img{aspect-ratio:4/5}.ar-atelier-image{margin-bottom:28px}.ar-atelier-meta{left:14px;bottom:-28px}.ar-footer{display:block;text-align:center}.ar-footer nav{justify-content:center;margin:34px 0}.ar-footer small{display:block}.ar-mobile-menu{position:fixed;display:flex;flex-direction:column;justify-content:center;inset:0;background:var(--ivory);z-index:19;padding:100px 34px;transform:translateX(100%);transition:transform .5s ease}.ar-mobile-menu.open{transform:translateX(0)}.ar-mobile-menu a{font-family:'Playfair Display',serif;color:var(--burg);font-size:42px;text-decoration:none;padding:15px 0;border-bottom:1px solid rgba(74,20,32,.15)}.ar-mobile-menu .ar-mobile-kicker{font:9px 'DM Sans',sans-serif;letter-spacing:.25em;text-transform:uppercase;color:var(--mgold);margin-bottom:27px}.ar-search{top:72px}}
      `}</style>
      <header className={`ar-nav ${scrolled ? "is-scrolled" : ""}`}>
        <a className="ar-wordmark" href="#top" aria-label="Avelin Rouge home">AVELIN ROUGE<small>MAISON DE COUTURE</small></a>
        <nav className="ar-links" aria-label="Primary"><a href="#house">The House</a><a href="#world">The World</a><a href="#journal">Journal</a><a href="#collections">Shop</a></nav>
        <div className="ar-utils" aria-label="Utilities">
          <button aria-label="Wishlist"><Icon kind="heart" /></button><button aria-label="Search" onClick={() => setSearch(!search)}><Icon kind="search" /></button><button aria-label="Account"><Icon kind="user" /></button><button aria-label="Bag"><Icon kind="bag" /></button><button className="ar-menu-btn" aria-label="Open menu" onClick={() => setMenu(true)}><Icon kind="menu" /></button>
        </div>
      </header>
      <div className={`ar-search ${search ? "open" : ""}`} role="search"><label htmlFor="ar-search-input">Search the maison</label><input id="ar-search-input" type="search" placeholder="Search" autoFocus={search} /></div>
      <div className={`ar-mobile-menu ${menu ? "open" : ""}`} aria-label="Mobile navigation"><button onClick={closeMenu} aria-label="Close menu" style={{position:"absolute",top:25,right:25,background:"none",border:0,color:"var(--burg)"}}><Icon kind="close"/></button><span className="ar-mobile-kicker">The private digital front door</span><a href="#house" onClick={closeMenu}>The House</a><a href="#world" onClick={closeMenu}>The World</a><a href="#journal" onClick={closeMenu}>Journal</a><a href="#collections" onClick={closeMenu}>Shop</a></div>
      <main id="top">
        <section className="ar-hero"><img className="ar-hero-img" src={`${IMG}avelin-house.jpg`} alt="The Avelin Rouge house at dusk" /><div className="ar-hero-content"><div className="ar-hero-kicker">Since 1896 · Paris / The Cotswolds</div><h1>A quiet<br /><em>force.</em></h1><p className="ar-hero-note">A house of considered silhouettes, made slowly for those who know the difference.</p></div><div className="ar-scroll">Enter the house</div></section>
        <Reveal><section id="house" className="ar-section ar-story"><div className="ar-story-copy"><Eyebrow>The House / Est. 1896</Eyebrow><h2 className="ar-display">A lineage of<br />beautiful restraint.</h2><p className="ar-body">Avelin Rouge began in a quiet Parisian courtyard, where Madeleine Avelin cut her first coat by hand. Four generations later, the house remains an intimate conversation between memory and the present.</p><a className="ar-link" href="#vision">Read our story</a></div><div className="ar-story-image"><img src={`${IMG}avelin-house.jpg`} alt="Limestone architecture of the Avelin Rouge house" /></div></section></Reveal>
        <Reveal><section id="vision" className="ar-section ar-vision"><div className="ar-vision-image"><img src={`${IMG}avelin-founder.jpg`} alt="Founder of Avelin Rouge in the atelier" /></div><div className="ar-vision-copy"><Eyebrow>The Founder's Vision</Eyebrow><blockquote className="ar-quote">“Clothing should not announce a woman. It should make room for her.”</blockquote><p className="ar-body">Elise Avelin protects the house’s original instinct: to make fewer things, with more feeling. Her vision is not nostalgia, but a form of attention — to the body, the cloth, and the life that will be lived in it.</p><div className="ar-signature">Elise Avelin</div></div></section></Reveal>
        <Reveal><section className="ar-section ar-pillars"><Eyebrow>The Avelin Standard</Eyebrow><h2 className="ar-display">Three gestures.<br />One signature.</h2><div className="ar-pillar-grid"><div className="ar-pillar"><span className="ar-pillar-index">01 — THE CUT</span><h3>Architecture for the body</h3><p>Every line is drawn to follow movement, never to constrain it.</p></div><div className="ar-pillar"><span className="ar-pillar-index">02 — THE CLOTH</span><h3>Materials with a memory</h3><p>Rare wools, washed silks, and linens chosen for how they age.</p></div><div className="ar-pillar"><span className="ar-pillar-index">03 — THE HAND</span><h3>Time, made visible</h3><p>Each piece passes through the hands of one dedicated artisan.</p></div></div></section></Reveal>
        <Reveal><section id="collections" className="ar-section ar-collections"><div className="ar-collection-intro"><div><Eyebrow>From the Journal</Eyebrow><h2 className="ar-display">The collections.</h2></div><a className="ar-link" href="#journal">Enter the journal</a></div><div className="ar-collection-grid"><a className="ar-collection" href="#journal"><div className="ar-collection-visual"><img src={`${IMG}avelin-courtship.jpg`} alt="The Courtship Collection editorial" /></div><div className="ar-collection-label"><h3>The Courtship Collection</h3><span>View story →</span></div></a><a className="ar-collection" href="#journal"><div className="ar-collection-visual"><img src={`${IMG}avelin-founder.jpg`} alt="The Lingering Hour Collection editorial" /></div><div className="ar-collection-label"><h3>The Lingering Hour Collection</h3><span>View story →</span></div></a><a className="ar-collection" href="#journal"><div className="ar-collection-visual"><img src={`${IMG}avelin-house.jpg`} alt="The Riders Quadrant Collection editorial" /></div><div className="ar-collection-label"><h3>The Riders Quadrant Collection</h3><span>View story →</span></div></a></div></section></Reveal>
        <Reveal><section id="world" className="ar-section ar-atelier"><div className="ar-atelier-copy"><Eyebrow>The World / The Atelier</Eyebrow><h2 className="ar-display">Where a garment<br />learns to breathe.</h2><p className="ar-body">In our Cotswolds atelier, a jacket is given the patience of a conversation. Pattern cutters, embroiderers and tailors work in a shared silence, shaping cloth into something unmistakably alive.</p><a className="ar-link" href="#appointment">Discover the atelier</a></div><div className="ar-atelier-image"><img src={`${IMG}avelin-atelier.jpg`} alt="Avelin Rouge artisan hand-stitching a jacket" /><div className="ar-atelier-meta">The hand remembers.</div></div></section></Reveal>
        <Reveal><section id="appointment" className="ar-appointment"><Eyebrow>A private invitation</Eyebrow><h2 className="ar-display">The door is open<br />when you are ready.</h2><p>Discover Avelin Rouge in a private appointment, by invitation or arrangement at our maisons in Paris and London.</p><a className="ar-cta" href="#footer">Request an appointment</a></section></Reveal>
      </main>
      <footer id="footer" className="ar-footer"><a className="ar-wordmark" href="#top">AVELIN ROUGE<small>MAISON DE COUTURE</small></a><nav><a href="#house">The House</a><a href="#world">The World</a><a href="#journal">Journal</a></nav><small>© 2025 Avelin Rouge · Paris</small></footer>
    </div>
  );
}